clothing_store/catalog/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'catalog'

urlpatterns = [
    path('', Product.as_view(), name='products'),
    path('categories/<slug:cat_slug>/', Product.as_view(), name='cat_products'),
    path('<slug:prod_slug>/', ShowProduct.as_view(), name='one_product'),

]

clothing_store/clothing_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothing_store/orders/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'orders'

urlpatterns = [
    path('<int:pk>/', ShowOrder.as_view(), name='one_order'),
    path('', Orders.as_view(), name='orders'),
    path('create/', CreateOrderView.as_view(), name='create_order'),

]

clothing_store/users/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'users'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),

]

handler404 = pageNotFound

clothing_store/orders/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

from catalog.models import *


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('new', 'Новый'),
        ('processing', 'В обработке'),
        ('ready', 'Готов'),
        ('received', 'Получен'),
    ]
    ORDER_STATUS_DICT = dict(ORDER_STATUS_CHOICES)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='new')

    def __str__(self):
        return f'Order {self.id} by {self.customer.username}'

    class Meta:
        ordering = ['date']

    @property
    def status_display(self):
        return self.ORDER_STATUS_DICT.get(self.status)

    @property
    def product_name(self):
        return self.product.name

    @property
    def total_price(self):
        return sum(item.price for item in self.orderitem_set.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()

    def __str__(self):
        return f'{self.product.name} (x{self.quantity}) for order {self.order.id}'

    class Meta:
        ordering = ['product']

clothing_store/orders/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Order, OrderItem


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product', 'quantity']

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        product = self.cleaned_data['product']
        if quantity > product.quantity:
            raise ValidationError(f'Максимально возможный заказ {product.quantity}')
        if quantity <= 0:
            raise ValidationError(f'Количество должно быть больше 0')
        return quantity


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'phone']


OrderItemFormSet = forms.models.inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1, can_delete=False)

clothing_store/orders/views.py
from django.core.exceptions import ValidationError
from django.db import transaction
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView

from .forms import OrderForm, OrderItemFormSet
from .models import *
from users.utils import *

from catalog.models import Products


class ShowOrder(DataMixin, DetailView):
    model = Order
    template_name = 'orders/order.html'
    context_object_name = 'order'

    def get_object(self):
        return Order.objects.filter(pk=self.kwargs['pk']).first()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.get_object()
        order_items = OrderItem.objects.filter(order=order)

        context['order_items'] = order_items
        c_def = self.get_user_context(title="Заказ")
        context.update(c_def)
        return context


class Orders(DataMixin, ListView):
    model = Order
    template_name = 'orders/orders.html'
    context_object_name = 'orders'
    ordering = 'status'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.all()
        else:
            return Order.objects.filter(customer=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Список заказов")
        context.update(c_def)
        return context


class CreateOrderView(DataMixin, View):
    model = Order


    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
        order_form = OrderForm()
        order_item_formset = OrderItemFormSet()
        context = self.get_context_data(order_form=order_form, order_item_formset=order_item_formset)
        return render(request, 'orders/create_order.html', context)

    def post(self, request):
        order_form = OrderForm(request.POST)
        order_item_formset = OrderItemFormSet(request.POST)
        if order_form.is_valid() and order_item_formset.is_valid():
            try:
                with transaction.atomic():
                    order = order_form.save(commit=False)
                    if request.user.is_authenticated:
                        order.customer = request.user
                        order.save()
                    else:
                        return redirect('users:login')

                    order_items = order_item_formset.save(commit=False)

                    product_quantities = {}

                    for item in order_items:
                        item.order = order
                        item.price = item.product.price * item.quantity  # расчет стоимости продукта в заказе

                        # Обновляем количество продуктов
                        if item.product.id in product_quantities:
                            product_quantities[item.product.id] += item.quantity
                        else:
                            product_quantities[item.product.id] = item.quantity

                    for product_id, quantity in product_quantities.items():
                        product = Products.objects.get(id=product_id)
                        if product.quantity < quantity:
                            raise ValidationError(f'Недостаточное количество продукта "{product.name}" на складе.')

                    # Сохраняем все items после проверки доступного количества
                    for item in order_items:
                        item.save()

                    # Обновляем количество продуктов на складе
                    for product_id, quantity in product_quantities.items():
                        product = Products.objects.get(id=product_id)
                        product.quantity -= quantity
                        product.save()

                    return redirect('orders:orders')  # перенаправление на страницу с заказами после успешного создания

            except ValidationError as e:
                # seen_products = set()
                # for item in order_item_formset.forms:
                #     if item.cleaned_data and not item.cleaned_data.get('DELETE'):
                #         product_id = item.cleaned_data['product'].id
                #         if product_id in seen_products:
                #             item.cleaned_data['DELETE'] = True
                #         else:
                #             item.cleaned_data['quantity'] = 1
                #             seen_products.add(product_id)

                context = self.get_context_data(order_form=order_form, order_item_formset=OrderItemFormSet(), error=e.message)
                return render(request, 'orders/create_order.html', context)

        context = self.get_context_data(order_form=order_form, order_item_formset=order_item_formset)
        return render(request, 'orders/create_order.html', context)

clothing_store/orders/templates/orders/create_order.html
{% extends 'users/base.html' %}

{% block content %}
<h1>Создать заказ</h1>

<form id="order-form" method="post">
    {% csrf_token %}
    {{ order_form.as_p }}
    <fieldset id="order-items">
        {{ order_item_formset.management_form }}
        <h2>Продукты</h2>
        <div id="formset">

            {% if error %}
                <div class="error">{{ error }}</div>
            {% endif %}

            {% for form in order_item_formset %}
                <div class="formset-row">
                    {{ form.as_p }}
                    <button type="button" class="delete-row">Удалить</button>
                </div>
            {% endfor %}
        </div>
        <button type="button" class="add-row">Добавить продукт</button>
    </fieldset>
    <button type="submit">Создать заказ</button>
</form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<div id="empty-form-template" style="display: none;">
    {% with empty_form=order_item_formset.empty_form %}
        <div class="formset-row">
            {{ empty_form.as_p }}
            <button type="button" class="delete-row">Удалить</button>
        </div>
    {% endwith %}
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    var form_idx = $('#id_orderitem_set-TOTAL_FORMS').val();

    $('.add-row').click(function() {
        var newForm = $('#empty-form-template').html().replace(/__prefix__/g, form_idx);
        $('#formset').append(newForm);
        form_idx++;
        $('#id_orderitem_set-TOTAL_FORMS').val(form_idx);
    });

    $(document).on('click', '.delete-row', function() {
        $(this).closest('.formset-row').remove();
        var forms = $('.formset-row');
        $('#id_orderitem_set-TOTAL_FORMS').val(forms.length);
        forms.each(function(index, form) {
            $(form).find(':input').each(function() {
                updateElementIndex(this, index);
            });
        });
    });

    function updateElementIndex(el, index) {
        var id_regex = new RegExp('(id_orderitem_set-\\d+-)');
        var replacement = 'id_orderitem_set-' + index + '-';
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
});
</script>
{% endblock %}

clothing_store/orders/templates/orders/order.html
{% extends 'users/base.html' %}
{% block content %}
                    <h1>Заказ №{{ order.id }}</h1>
                    <strong>Статус:</strong> {{ order.status_display}}</p>
                    <strong>Дата:</strong> {{ order.date }}</p>
                    <strong>Адрес:</strong> {{ order.address }}</p>
                    <strong>Телефон:</strong> {{ order.phone }}</p>
<h2>Продукты в заказе</h2>
<ul>
    {% for item in order_items %}
    <li>
        <a href="{% url 'catalog:one_product' item.product.slug %}">
            <strong>{{ item.product.name }}</strong><br>
        </a>
        Количество: {{ item.quantity }}<br>
        Цена за единицу: {{ item.product.price }}<br>
        Итоговая стоимость: {{ item.price }}
    </li>
    {% endfor %}
</ul>

{% endblock %}

clothing_store/orders/templates/orders/orders.html
{% extends 'users/base.html' %}
{% block content %}
<h1>{{title}}</h1>
<ul class="order-list">
    {% for order in orders %}
    <li class="order-item">
        <div class="order-container">
            <a href="{% url 'orders:one_order' order.pk %}">
                <strong>Заказ № </strong> {{ order.pk }}<br>
            </a>
            <strong>Статус:</strong> {{ order.status_display }}<br>
            <strong>Заказчик:</strong> {{ order.customer }}<br>
            <strong>Адрес:</strong> {{ order.address }}<br>
            <strong>Сумма заказа:</strong> {{ order.total_price }}<br>
            <strong>Дата:</strong> {{ order.date }}<br>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}