clothing_store/catalog/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'catalog'

urlpatterns = [
    path('', Product.as_view(), name='products'),
    path('categories/<slug:cat_slug>/', Product.as_view(), name='cat_products'),
    path('<slug:prod_slug>/', ShowProduct.as_view(), name='one_product'),

]

clothing_store/clothing_store/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('catalog.urls', namespace='catalog')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('users.urls', namespace='users')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothing_store/orders/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'orders'

urlpatterns = [
    path('<int:pk>/', ShowOrder.as_view(), name='one_order'),
    path('', Orders.as_view(), name='orders'),
    path('create/', CreateOrderView.as_view(), name='create_order'),

]

clothing_store/users/urls.py
from django.urls import path, re_path

from .views import *

app_name = 'users'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),

]

handler404 = pageNotFound

clothing_store/users/models.py
from django.contrib.auth.models import User

clothing_store/users/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotFound
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import  CreateView, TemplateView

from .utils import *


class Home(DataMixin, TemplateView):
    template_name = 'users/home.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Главная страница")
        context.update(c_def)
        return context


class RegisterUser(DataMixin, CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        context.update(c_def)
        return context

    def form_invalid(self, form):
        messages.error(self.request, 'Пользователь с таким именем уже существует')
        return super().form_invalid(form)


class LoginUser(DataMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        context.update(c_def)
        return context

    def get_success_url(self):
        return reverse_lazy('users:home')


def logout_user(request):
    logout(request)
    return redirect('users:login')


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

clothing_store/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<table class="table-page" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td valign="top" class="categories">
            {% block mainmenu %}
            <ul id="mainmenu" class="mainmenu">
                <div class="mainmenu__about">
                    {% for m in menu %}
                    <li><a href="{% url 'users:'|add:m.url_name %}">{{m.title}}</a></li>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                    <li class="last"> {{user.username}} | <a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                    <li class="last"><a href="{% url 'users:register' %}">Регистрация</a> | <a href="{% url 'users:login' %}">Войти</a> </li>
                    {% endif %}
                </div>
                <li><a href="{% url 'orders:create_order' %}">Заказать</a>
                {% if request.user.is_authenticated %}
                | <a href="{% url 'orders:orders' %}">Заказы</a> {% endif %}
                </li>
            </ul>
            <div class="clear"></div>
            {% endblock mainmenu %}


            <table class="table-content" border=0 cellpadding="0" cellspacing="0">
                <tr>
                    <!-- Sidebar слева -->
                    <td valign="top" class="left-chapters">
                        <ul id="leftchapters">
                            {% if request.resolver_match.url_name == 'products' and cat_selected == 0 %}
                                <li class="selected">Все категории</li>
                            {% else %}
                                <li><a href="{% url 'catalog:products' %}">Все категории</a></li>
                            {% endif %}

                            {% for c in cats %}
                                {% if c.products__count > 0 %}
                                {% if c.pk == cat_selected %}
                                <li class="selected">{{c.name}}</li>
                                {% else %}
                                <li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
                                {% endif %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                    <td valign="top" class="content">
                        <div class="content-text">
                            {% block content %}
                            {% endblock %}
                            {% if page_obj.has_other_pages %}
                            <nav class="pagination-nav">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li class="page-num">
                                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&lt;</a>
                                    </li>
                                    {% endif %}
                                    {% for p in page_obj.paginator.page_range %}
                                    {% if page_obj.number == p %}
                                    <li class="page-num page-num-selected">{{ p }}</li>
                                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                                    <li class="page-num">
                                        <a href="?page={{ p }}" class="page-link">{{ p }}</a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li class="page-num">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&gt;</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </nav>
                            {% endif %}
                        </div>
                        <!-- Конец блока контента -->

                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>

clothing_store/users/templates/users/home.html
{% extends 'users/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 <h1>Добро пожаловать в наш магазин!</h1>
  <p>Здесь вы найдете лучшие товары по самым выгодным ценам. Мы предлагаем широкий ассортимент продукции и стремимся обеспечить наилучший сервис для наших клиентов.</p>
  <p>Наш магазин гордится высоким качеством товаров и отличным обслуживанием клиентов. Независимо от того, что вы ищете, мы уверены, что у нас есть то, что вам нужно.</p>
{% endblock %}

clothing_store/users/templates/users/login.html
{% extends 'users/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
</form>
 
{% endblock %}

clothing_store/users/templates/users/register.html
{% extends 'users/base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
</form>
 {% if form.errors %}
    <div class="error">
        {% for field, errors in form.errors.items %}
            <p>{{ field }}: {{ errors }}</p>
        {% endfor %}
    </div>
{% endif %}
{% endblock %}